export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN_SUCCESSFUL = 'RECEIVE_LOGIN_SUCCESSFUL';
export const RECEIVE_LOGIN_FAILURE = 'RECEIVE_LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const REQUEST_CHANGE_PASSWD = 'REQUEST_CHANGE_PASSWD';
export const REQUEST_CHANGE_PASSWD_SUCCESSFUL = 'REQUEST_CHANGE_PASSWD_SUCCESSFUL';
export const REQUEST_CHANGE_PASSWD_FAILURE = 'REQUEST_CHANGE_PASSWD_FAILURE';

export const REQUEST_PERSON_PROFILE = 'REQUEST_PERSON_PROFILE';
export const REQUEST_PERSON_PROFILE_SUCCESSFUL = 'REQUEST_PERSON_PROFILE_SUCCESSFUL';
export const REQUEST_PERSON_PROFILE_FAILURE = 'REQUEST_PERSON_PROFILE_FAILURE';

export const SET_TOKEN = 'SET_TOKEN';

export const REQUEST_ASYNCSTORAGE_CHANGE = 'REQUEST_ASYNCSTORAGE_CHANGE';
export const ASYNCSTORAGE_SUCCESS = 'ASYNCSTORAGE_SUCCESS';
export const ASYNCSTORAGE_ERROR = 'ASYNCSTORAGE_ERROR';
export const SUBMIT_CONFIRM = 'SUBMIT_CONFIRM';

export const REQUEST_NEWS = 'REQUEST_NEWS';
export const REQUEST_NEWS_SUCCESSFUL = 'REQUEST_NEWS_SUCCESSFUL';
export const REQUEST_NEWS_FAILURE = 'REQUEST_NEWS_FAILURE';

export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const REQUEST_EVENTS_SUCCESSFUL = 'REQUEST_EVENTS_SUCCESSFUL';
export const REQUEST_EVENTS_FAILURE = 'REQUEST_EVENTS_FAILURE';

export const REQUEST_EVENT = 'REQUEST_EVENT';
export const REQUEST_EVENT_SUCCESSFUL = 'REQUEST_EVENT_SUCCESSFUL';
export const REQUEST_EVENT_FAILURE = 'REQUEST_EVENT_FAILURE';

export const REQUEST_SINGLE_NEWS = 'REQUEST_SINGLE_NEWS';
export const REQUEST_SINGLE_NEWS_SUCCESSFUL = 'REQUEST_SINGLE_NEWS_SUCCESSFUL';
export const REQUEST_SINGLE_NEWS_FAILURE = 'REQUEST_SINGLE_NEWS_FAILURE';

export const REQUEST_EVENTS_HEADLINE_SUCCESSFUL = 'REQUEST_EVENTS_HEADLINE_SUCCESSFUL';

export const REQUEST_EVENTS_ACTIVE_SUCCESSFUL = 'REQUEST_EVENTS_ACTIVE_SUCCESSFUL';
export const REQUEST_ACTIVE_EVENT = 'REQUEST_ACTIVE_EVENT';

export const REQUEST_ATTEND = 'REQUEST_ATTEND';
export const REQUEST_ATTEND_SUCCESSFUL = 'REQUEST_ATTEND_SUCCESSFUL';
export const REQUEST_ATTEND_FAILURE = 'REQUEST_ATTEND_FAILURE';

// export const GET_STORAGE_DATA = 'GET_STORAGE_DATA';
// export const GET_STORAGE_DATA_SUCCESS = 'GET_STORAGE_DATA_SUCCESS';
// export const GET_STORAGE_DATA_FAILURE = 'GET_STORAGE_DATA_FAILURE';