//User action type
export const REGISTER = 'REGISTER';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

//after show the error toast and then clear it
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR = 'CLEAR';

//clear token in the storage
export const CLEAR_TOKEN = 'CLEAR_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';




//main screen fetch data
//export const
//POSTS actions constants
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';


//single POST  actions constants
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const GET_SINGLE_POST_ERROR = 'GET_SINGLE_POST_ERROR';
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';

//HOSPITALS actions constants
export const GET_HOSPITALS = 'GET_HOSPITALS';
export const GET_HOSPITALS_ERROR = 'GET_HOSPITALS_ERROR';
export const GET_HOSPITALS_SUCCESS = 'GET_HOSPITALS_SUCCESS';


//single HOSPITAL  actions constants
export const GET_SINGLE_HOSPITAL = 'GET_SINGLE_HOSPITAL';
export const GET_SINGLE_HOSPITAL_ERROR = 'GET_SINGLE_HOSPITAL_ERROR';
export const GET_SINGLE_HOSPITAL_SUCCESS = 'GET_SINGLE_HOSPITAL_SUCCESS';

//single HOSPITAL DOCTOR LISTS actions constants
export const GET_SINGLE_HOSPITAL_DOCTORS = 'GET_SINGLE_HOSPITAL_DOCTORS';
export const GET_SINGLE_HOSPITAL_DOCTORS_ERROR = 'GET_SINGLE_HOSPITAL_DOCTORS_ERROR';
export const GET_SINGLE_HOSPITAL_DOCTORS_SUCCESS = 'GET_SINGLE_HOSPITAL_DOCTORS_SUCCESS';

//DOCTORS actions constants
export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_DOCTORS_ERROR = 'GET_DOCTORS_ERROR';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';

//DOCTORS actions constants
export const GET_SINGLE_DOCTOR = 'GET_SINGLE_DOCTOR';
export const GET_SINGLE_DOCTOR_ERROR = 'GET_SINGLE_DOCTOR_ERROR';
export const GET_SINGLE_DOCTOR_SUCCESS = 'GET_SINGLE_DOCTOR_SUCCESS';


//single DOCTORS INFO  actions constants
export const GET_SINGLE_DOCTOR_INFO = 'GET_SINGLE_DOCTOR_INFO';
export const GET_SINGLE_DOCTOR_INFO_ERROR = 'GET_SINGLE_DOCTOR_INFO_ERROR';
export const GET_SINGLE_DOCTOR_INFO_SUCCESS = 'GET_SINGLE_DOCTOR_INFO_SUCCESS';

//single DOCTORS FAV  actions constants
export const ADD_SINGLE_DOCTOR_FAV = 'ADD_SINGLE_DOCTOR_FAV';
export const ADD_SINGLE_DOCTOR_FAV_ERROR = 'ADD_SINGLE_DOCTOR_FAV_ERROR';
export const ADD_SINGLE_DOCTOR_FAV_SUCCESS = 'ADD_SINGLE_DOCTOR_FAV_SUCCESS';

//single DOCTORS ANSWERS actions constants
export const GET_SINGLE_DOCTOR_ANSWERS = 'GET_SINGLE_DOCTOR_ANSWERS';
export const GET_SINGLE_DOCTOR_ANSWERS_ERROR = 'GET_SINGLE_DOCTOR_ANSWERS_ERROR';
export const GET_SINGLE_DOCTOR_ANSWERS_SUCCESS = 'GET_SINGLE_DOCTOR_ANSWERS_SUCCESS';

//single DOCTORS COMMENTS actions constants
export const GET_SINGLE_DOCTOR_COMMENTS = 'GET_SINGLE_DOCTOR_COMMENTS';
export const GET_SINGLE_DOCTOR_COMMENTS_ERROR = 'GET_SINGLE_DOCTOR_COMMENTS_ERROR';
export const GET_SINGLE_DOCTOR_COMMENTS_SUCCESS = 'GET_SINGLE_DOCTOR_COMMENTS_SUCCESS';

//single DOCTORS  CREATE COMMENTS actions constants
export const CREATE_SINGLE_DOCTOR_COMMENTS = 'CREATE_SINGLE_DOCTOR_COMMENTS';
export const CREATE_SINGLE_DOCTOR_COMMENTS_ERROR = 'CREATE_SINGLE_DOCTOR_COMMENTS_ERROR';
export const CREATE_SINGLE_DOCTOR_COMMENTS_SUCCESS = 'CREATE_SINGLE_DOCTOR_COMMENTS_SUCCESS';



